# Generated by Django 3.2.16 on 2022-12-05 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marigarated', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test1',
        ),
        migrations.DeleteModel(
            name='Test2',
        ),
        migrations.DeleteModel(
            name='Test3',
        ),
    ]
